site_name: Pookie Code
site_url: https://pookiecode.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    scheme: youtube
extra_css:
  - extra.css
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
plugins:
  - search
  - mermaid2

